eclipse-basyx/basyx-python-sdk

- basyx/aas/adapter/json/json_serialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- basyx/aas/model/base.py
- basyx/aas/model/provider.py
- test/adapter/xml/test_xml_deserialization.py
This PR provides various minor fixes and codestyle improvements:
- fix a minor docstring error for `get_identifiable()` of `model.provider.AbstractObjectProvider`
- fix `AdministrativeInformation.__eq__` to return `NotImplemented` if other object isn't of type `AdministrativeInformation`
- replace `if` with `elif` in XML and JSON serialization to avoid unnecessary checks
- shorten XML deserialization test a bit
> Various minor fixes

- README.md
The location of the DotAAS specification has been changed on the
plattform-i40.de server. Because the old link is no longer valid,
this commit updates the link to point to the new location.
> readme: update DotAAS spec link

- basyx/aas/backend/local_file.py
- test/backend/test_local_file.py
This PR adds a local file backend, which stores `Identifiable` objects as JSON files on the local machine. 
The functionality is pretty much copied from the `backend.couchdb`, with the CouchDB revision conflict checking removed, therefore, there is no way of conflict handling with this backend (e.g. every commit actually overwrites the JSON file)
As a file name, I decided to use the SHA256 sum of the Identifier (since URIs like for the CouchDB make for bad file names in most OSs).
The `source` attribute is a valid URI, following the schema: 
```
file://localhost/path/to/folder/<sha256sum>.json
```
> Add a local file backend

- basyx/aas/compliance_tool/compliance_check_aasx.py
When deserializing an aasx package using the compliance tool, some outputs are missing. This is because only the errors logged during package extraction are captured but not the ones from the subsequent deserializations (json/xml).
> Compliance tool: fix missing outputs for aasx deserialization

- .github/workflows/ci.yml
- README.md
- test/compliance_tool/test_aas_compliance_tool.py
Link documentation in README and state requirement of signing the ECA before contributing code to the project.
Also update some module names from "aas.*" to "basyx.aas.*" in the README.
Additionally this PR enables setting the `PYTHONPATH` when running the compliance tool in the tests. It is no longer required to manually set `PYTHONPATH` when running the tests with `python -m unittest` or `coverage`. Thus don't set `PYTHONPATH` in the CI script anymore.
Furthermore abstract running the compliance tool with a function, eliminating a lot of duplicate code.
> Update README and set PYTHONPATH in compliance tool tests

- README.md
This PR extends the readme by the sphinx dependencies required to build the documentation.
> readme: add dependencies for building the documentation

- basyx/aas/compliance_tool/compliance_check_aasx.py
- basyx/aas/examples/tutorial_backend_couchdb.py
- basyx/aas/examples/tutorial_serialization_deserialization.py
- basyx/aas/examples/tutorial_storage.py
- basyx/aas/model/base.py
- test/adapter/aasx/test_aasx.py
- test/adapter/json/test_json_serialization.py
- test/adapter/json/test_json_serialization_deserialization.py
- test/adapter/xml/test_xml_serialization.py
- test/model/test_base.py
Since version 2.9.0, pycodestyle requires a whitespace after every keyword.
> add whitespace after assert keyword

- .github/workflows/ci.yml
- setup.py
- test/compliance_tool/test_compliance_check_aasx.py
In order to update the dependency on jsonschema (https://github.com/eclipse-basyx/basyx-python-sdk/commit/80913ef9ad5dc1bbf673b84acbc54dbfc1a3915f), Python 3.6 must be dropped. Python 3.6 is EOL since 23.12.2021 and all major distributions have updated to more recent releases.
Also disable skipping of a unit test on Python versions < 3.7, since this is no longer supported and tested anyways.
This PR is required by #24.
> Drop support for Python 3.6

- test/compliance_tool/test_compliance_check_aasx.py
- test/compliance_tool/test_compliance_check_json.py
- test/compliance_tool/test_compliance_check_xml.py
Improve strictness of wrong_attribute tests by checking the whole error message instead just for a single error, which previously disregarded any additional errors.
> test.compliance_tool: improve wrong_attribute test strictness

- requirements.txt
This dependency is updated to fix a DeprecationWarning when running the unittests:
```
DeprecationWarning: The metaschema specified by $schema was not found.
Using the latest draft to validate, but this will raise an error in the future
```
This warning was logged because jsonschema didn't have support for
schema version 2019-09 in versions <4.
This requires #40 to be merged.
> requirements: update jsonschema to 4.7

- basyx/aas/examples/data/_helper.py
Fix an IndexError that would be raised when comparing lists of OperationVariables of different length. While the length is checked in advance, it doesn't necessarily abort execution if raise_immediately is False.
> examples: fix a possible IndexError

- .github/workflows/ci.yml
Python 3.11 has been released on 24.10.2022 and we should aim to be fully compatible, thus test on 3.11 instead of 3.10. Also test on 3.9 instead of 3.8, because 3.9 is more widespread than 3.8 (e.g. 3.9 is packaged for Debian 11 (bullseye), most other distributions either use 3.9 or a newer release as well) and so we're back to the (test, skip, test, skip, test) pattern, where we skip testing on 3.8 and 3.10.
> ci: update python versions in strategy matrix

- basyx/aas/backend/couchdb.py
DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTResponse.headers.get(name, default).
Same as #44, CI fails until #43 is merged.
> backend.couchdb: remove usage of deprecated HTTPResponse.getheader()

- basyx/aas/model/base.py
- test/model/test_base.py
Previously resolved keys beside the identifier of the identifiable weren't added to the `resolved_keys` list. This fixes this issue, similar to how it's done on the improve/V30RC02 branch. CI checks fail because of #43.
> model.base: fix AASReference.resolve() error messages

- basyx/aas/model/datatypes.py
The following classes were missing from the implementation, because only XML
1.0 datatypes have been implemented so far:
`yearMonthDuration` is a restriction of duration, were only years
and months are allowed.
`dayTimeDuration` is a restriction of duration, were specifying
years and months is not allowed.
`dateTimeStamp` is a restriction of dateTime, were the timezone is
required.
yearMonthDuration and dayTimeDuration are implemented as subclasses of
Duration. The constraints are only checked on serialization, which makes
it a bit hacky. However, since this commit will be reverted with DotAAS
3.0 anyways, it's good enough for now.
Close #49
Furthermore, this PR removes an unused definition and fixes a typo. Obviously, these commits shouldn't be reverted with 3.0.
> model.datatypes: Implement missing types for XML 1.1 compatibility

- setup.py
Since a recent version, wheel requires a comma between lower and upper version bound.
> setup.py: add missing comma to urllib3 dependency specification

- test/model/test_base.py
This PR renames `base.AASReference` to `base.ModelReference` to suit V3.0
> Rename `base.AASReference` to `ModelReference`

- test/model/test_base.py
Renamed `model.KeyElements` to `model.KeyTypes` as defined for V3.0RC02 and V3.0. Adapted to new constructor of `model.Key`
see: https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=171
> test.model: Rename `model.KeyElements` to `model.KeyTypes`

- basyx/aas/adapter/xml/xml_deserialization.py
When deserializing XML we would previously only have a look at the first child of an unnecessary wrapper element and ignore additional elements. However, since some implemenetations like the AASX Package Explorer generate schema-incompatible XML, this behavior is changed in a way such that additional elements are no longer ignored, but also parsed instead.
Fix #71
> adapter.xml.xml_deserialization: be more forgiving with invalid input

- basyx/aas/adapter/_generic.py
- basyx/aas/adapter/json/aasJSONSchema.json
- basyx/aas/adapter/xml/AAS.xsd
- basyx/aas/model/base.py
Version 3.0 of the specification introduces a new enum `NOTAPPLICABLE` in `base.AssetKind`.
Further, we update the description of  `AssetKind/Type` and `AssetKind/Instance` as specified in  IEC 63278-1.
`NOTAPPLICABLE` is also added to `_generic.ASSET_KIND` dictionary.
see:
https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=164
https://industrialdigitaltwin.org/wp-content/uploads/2023/04/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=166
> `base.AssetKind`: Add newly introduced enum `NOTAPPLICABLE` and update description

- basyx/aas/model/base.py
- basyx/aas/model/submodel.py
- docs/source/constraints.rst
Version 3.0 reformulates multiple Constraints.
Reformulations that are connected to updates on Version 3.0 are listed and NOT changed yet.
I recommend to reformulate the constraints as part of the update.
Reformulations:
* 6
* 7
* 12
* 20
* 109
* 115
* 118
* 121
* 122
* 123
* 124
* 125
* 126
* 127
t.b.d. with other updates:
* 2 (Referable/idShort)
* 5 (AdministrativeInformation/version)
* 77 (Extension/name)
Constrains that have not been implemented yet and therefore have not been reformulated:
* 119
* 120
> Reformulate Constraints for V3.0

- test/backend/test_couchdb.py
- test/model/test_base.py
If an assertion is contained within the same context as a statement, that raises an error, the assertion is never executed, because the raised error leaves the context.
> test: fix accidentally disabled tests

- basyx/aas/adapter/json/json_deserialization.py
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/examples/data/_helper.py
- basyx/aas/examples/data/example_aas.py
- basyx/aas/examples/data/example_aas_missing_attributes.py
- basyx/aas/examples/data/example_submodel_template.py
This partially reverts 77c33e773b3e22365627c1f59ed2d5e09fd12ea0. The attribute is only removed from `SubmodelElement`s in the spec, but the commit also removes deserialization of the `kind`-Attribute for `Submodels` and some `kind` attributes of `Qualifier`s and `Submodel`s in the examples.
> Partially revert "Remove attribute `kind` from `SubmodelElement`"

- basyx/aas/model/datatypes.py
- test/model/test_datatypes.py
This adds `Decimal` parsing to the `from_xsd()` function of `model.datatypes`.
During construction of a `Decimal`, an `InvalidOperation` exception may occur. Since the user only expects a `ValueError` from this function, because all other parsers only raise `ValueError`s, the `InvalidOperation` error-type is handled and re-raised as a `ValueError`.
Fix #99
Furthermore, some basic tests for decimal serialization and deserialization are added.
The static analysis of this PR currently fails because of #100.
> model.datatypes: add `Decimal` parsing

- basyx/aas/model/__init__.py
Mypy appears to not like abstract classes in a context where only concrete classes should be given:
```
Only concrete class can be given where
"tuple[type[Referable], KeyTypes]" is expected
```
However, the [spec](https://industrialdigitaltwin.org/wp-content/uploads/2023/06/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=84) demands the three abstract classes
- `EventElement`
- `DataElement`
- `SubmodelElement`
to appear inside the `model.KeyTypes` Enum.
Therefore, we ignore these errors via `# type: ignore`.
This fixes the mypy error in #104
> model.KeyTypes: Ignore mypy errors for abstract classes to be compliant to spec

- basyx/aas/model/__init__.py
Mypy appears to not like abstract classes in a context where only concrete classes should be given:
```
Only concrete class can be given where
"tuple[type[Referable], KeyTypes]" is expected
```
However, the spec demands the four abstract classes
- `Event`
- `DataElement`
- `SubmodelElement`
- `SubmodelElementCollection`
to appear inside the `model.KeyTypes` Enum.
Therefore, we ignore these errors via `# type: ignore`.
This is the same fix as #105, just for the `main`-branch this time.
> model.KeyTypes: Ignore mypy errors for abstract classes to be compliant

- basyx/aas/adapter/json/json_serialization.py
Since `LangStringSet` was changed to be an own class in a1aaec350c172cb5d17a6917087be7c4a8b076ec, we can check for a `LangStringSet` via `isinstance()` now and simplify the JSON serialization.
> adapter.json: improve `LangStringSet` json serialization

- basyx/aas/model/base.py
Version 3.0 of the specification reformulates AASd-005:
> If AdministrativeInformation/version is not specified,
AdministrativeInformation/revision shall also be unspecified. 
This means that a revision requires a version. If there is no version,
there is no revision. Revision is optional.
> model.AdministrativeInformation: Update formulation of AASd-005 to v3.0

- basyx/aas/model/base.py
Version 3.0 of the specification removes AASd-100:
> Since new string types with length constraints were added, 
this constraint is no longer needed
> Constraint AASd-100: An attribute with data type "string" 
is not allowed to be empty
> model.base: Remove occurrences of deprecated constraint AASd-100

- basyx/aas/adapter/xml/xml_deserialization.py
The xml deserialization fails when xml tags without prefixes are used.
> Fixed xml deserialization for missing prefixes

- basyx/aas/model/base.py
- basyx/aas/model/submodel.py
- test/examples/test_helpers.py
- test/model/test_submodel.py
Since AASd-120 prohibits specifying id_shorts of direct children of
`SubmodelElementLists`, this commit adjusts `Referable.__repr__()` such
that the index of the element in the corresponding list is returned
instead.
Furthermore, the tests are adjusted accordingly.
> model.base: fix `Referable.__repr__()` for `SubmodelElementList`-children

- basyx/aas/model/base.py
If an item has been found, it doesn't make any sense to continue iterating the remaining items. Thus, this `continue` is replaced by a `break`, to break out of the loop once an item has been found.
> model.base: replace `continue` with `break` in `NamespaceSet.remove()`

- basyx/aas/adapter/json/json_deserialization.py
Previously, `AASConstraintViolation` exception weren't excepted in the json deserialization, breaking failsafe parsing whenever a constraint is violated. This commit ports edf5f27032b94535f15b66f2bafd5744e29e04a9 to the json deserialization.
> adapter.json.json_deserialization: handle `AASConstraintViolation`

- basyx/aas/model/base.py
- test/model/test_base.py
Some error messages raised in `ModelReference.resolve()` make use of the `resolved_keys` local list variable, which keeps track of all Identifiers, id_shorts and `SubmodelElementList` indices that have been resolved successfully.
Instead of `SubmodelElementList` indices, the children's id_shorts were added to this list previously, which is inconsistent, and soon would cease to work anyway, since AASd-120 prohibits specifying id_shorts for children of `SubmodelElementList`.
This commit fixes this such that indices are added and adjusts the tests accordingly.
> model.base: fix `ModelReference.resolve()` error messages for elements contained in `SubmodelElementLists`

- basyx/aas/adapter/json/json_deserialization.py
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- basyx/aas/model/base.py
- basyx/aas/model/submodel.py
- test/model/test_base.py
Since `SubmodelElementLists` require that their children elements don't
have `id_shorts`, they have to be made optional for all elements, but
required for `NamespaceSets`.
Furthermore, AASd-022 is changed from a `KeyError` to `AASConstraintViolation` and the
tests are adjusted accordingly.
Also, the NamespaceSet.add() identifier uniqueness check is moved
after the simple parent check for performance reasons, solely because
the parent check is a lot faster.
This PR depends on #127, #128 and #129.
> make `id_shorts` optional

- basyx/aas/model/datatypes.py
The AAS Manager uses typehints to generate a list of possible types for a value. Since `DateTimeStamp` was missing, it was impossible to store a `DateTimeStamp` value via AAS Manager.
> model.datatypes: add `DateTimeStamp` to `AnyXSDType`

- basyx/aas/model/base.py
- test/model/test_base.py
These hooks allow dynamically assigning a value to the identifying
attribute of an object whenever it is added to a `NamespaceSet`
(`item_id_set_hook`). Furthermore, the `item_id_del_hook` allows
unsetting the identifying attribute whenever an object is removed
from a `NamespaceSet`.
This functionality is necessary for the implementation of
`SubmodelElementLists`, because there we need to store items without
an identifying attribute in a `NamespaceSet`.
This PR depends on #130.
> model.base: add `item_id_{set,del}_hook` to `NamespaceSet`

- basyx/aas/model/base.py
Check if external_subject_id is ExternalReference
fixes #145
> Add Constraint AASd-133 in SpecificAssetId

- basyx/aas/model/base.py
- test/model/test_base.py
The default inherited `clear()` implementation repeatedly deletes the last item of the list until the list is empty. If the last item can be deleted successfully, but an item in front of it that will be deleted later cannot, this makes `clear()` non-atomic.
Thus, the `clear()` method is now overriden in an atomic way. Furthermore, the ConstrainedList atomicity test is fixed to correctly test for this as well.
> model.base: fix `ConstrainedList.clear()` atomicity

- basyx/aas/adapter/json/aasJSONSchema.json
- basyx/aas/adapter/json/json_deserialization.py
- basyx/aas/adapter/json/json_serialization.py
- basyx/aas/adapter/xml/AAS.xsd
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- basyx/aas/examples/data/_helper.py
- basyx/aas/examples/data/example_aas.py
- basyx/aas/examples/data/example_aas_mandatory_attributes.py
- basyx/aas/examples/tutorial_serialization_deserialization.py
- basyx/aas/model/aas.py
- basyx/aas/model/base.py
- basyx/aas/model/submodel.py
- test/adapter/json/test_json_deserialization.py
- test/adapter/xml/test_xml_deserialization.py
- test/compliance_tool/files/test_demo_full_example.json
- test/compliance_tool/files/test_demo_full_example.xml
- test/compliance_tool/files/test_demo_full_example_json_aasx/aasx/data.json
- test/compliance_tool/files/test_demo_full_example_wrong_attribute.json
- test/compliance_tool/files/test_demo_full_example_wrong_attribute.xml
- test/compliance_tool/files/test_demo_full_example_xml_aasx/aasx/data.xml
- test/compliance_tool/files/test_demo_full_example_xml_wrong_attribute_aasx/aasx/data.xml
- test/compliance_tool/files/test_deserializable_aas_warning.json
- test/compliance_tool/files/test_deserializable_aas_warning.xml
- test/model/test_aas.py
- test/model/test_base.py
- test/model/test_provider.py
- test/model/test_submodel.py
- Fixed Entity.specificAssetIds in JSON and XSD schemas
- Set `Entity.specific_asset_id` as `Iterable[SpecificAssetId]`, because the spec has changed
- Added check of constraint AASd-014 for Entity, see https://rwth-iat.github.io/aas-specs/AASiD/AASiD_1_Metamodel/index.html#Entity
- Added check of constraint AASd-131 for AssetInformation, see https://rwth-iat.github.io/aas-specs/AASiD/AASiD_1_Metamodel/index.html#AssetInformation
- Refactored de-/serialization of Entity
- Refactored deserialization of AssetInformation because of check of constraint AASd-131
- Refactored `check_entity_equal()`&`check_asset_information_equal()
- Updated test files
Fixes #144
> Make model.Entity.specific_asset_id a Set of model.SpecificAssetIds

- test/adapter/xml/test_xml_deserialization.py
This PR removes unneeded `# type: ignore` comments and improves the `OperationVariable` tests.
> improve `xml_deserilization` tests

- basyx/aas/model/_string_constraints.py
- test/model/test_string_constraints.py
Currently a string constraints decorator silently overwrites existing attributes in case of a naming conflict. This behavior is changed such that the decorator checks for existing attributes beforehand and raises an exception in case of a conflict.
Futhermore, tests for this behavior are added.
I noticed this problem when reviewing #149. There, the decorator for `Entity.global_asset_id` currently overwrites the `global_asset_id` property, resulting in the constraints not being checked properly. A fix for this is currently in the making.
> model._string_constraints: don't overwrite existing attributes in case of a conflict

- basyx/aas/model/base.py
- test/model/test_base.py
Refactor NamespaceSet
- Refactored `NamespaceSet.add()` as it was too big
  - Extracted some methods, in particular `_execute_item_del_hook`. I used the method also in other places
- As we check different constraints for uniqueness in the namespace, I defined ATTRIBUTES_CONSTRAINT_IDS. The dict will be used when throwing exception. The solution with the dict is temporary, we need other solution here.
- Use correct constraint ids for each NamespaceSet in tests, use "0" if not constraint id is suitable
> model.base: improve `NamespaceSet`

- basyx/aas/adapter/json/aasJSONSchema.json
- test/compliance_tool/files/test_demo_full_example.json
- test/compliance_tool/files/test_demo_full_example_json_aasx/aasx/data.json
- test/compliance_tool/files/test_demo_full_example_wrong_attribute.json
This updates the JSON Schema with the missing changes of the [specified schema](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/aas.json).
However, as noted in #72, we did not include the regex patterns for the `File`.
> adapter.json: Update Schema to comply with v3.0

- basyx/aas/adapter/json/aasJSONSchema.json
This removes the two XSD datatypes
- `xs:dateTimeStamp`
- `xs:dayTimeDuration`
from the `DataTypeDefXsd` in the JSON schema, as they were removed from the specification in v3.0
> adapter.json: Remove deprecated XSD DataTypes from Schema

- basyx/aas/adapter/xml/AAS.xsd
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- basyx/aas/examples/data/example_aas.py
- basyx/aas/model/base.py
- test/compliance_tool/files/test_demo_full_example.xml
- test/compliance_tool/files/test_demo_full_example_wrong_attribute.xml
- test/compliance_tool/files/test_demo_full_example_xml_aasx/aasx/data.xml
- test/compliance_tool/files/test_demo_full_example_xml_wrong_attribute_aasx/aasx/data.xml
This implements the missing changes to the XSD schema [from the specification v3.0](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/xml/AAS.xsd).
However, as noted in #72, we did not include the regex patterns for the `File`. 
Since this is quite a lot, I suggest looking at the single commits for the review.
> adapter.xml: Update XSD to v3.0

- basyx/aas/model/base.py
- test/model/test_base.py
Soften the language tag constraint
remove constraint, that if the second part of lang tag exists, it must be a region 
See https://github.com/eclipse-basyx/basyx-python-sdk/issues/157
> Soften the language tag constraint

- basyx/aas/adapter/json/json_deserialization.py
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/compliance_tool/cli.py
- basyx/aas/compliance_tool/compliance_check_aasx.py
- basyx/aas/compliance_tool/compliance_check_json.py
- basyx/aas/compliance_tool/compliance_check_xml.py
- basyx/aas/examples/data/_helper.py
- test/examples/test_helpers.py
Previously, the compliance tool would ignore `Extensions` of objects.
However, during the update to V3.0 and the changes to the JSON/XML
formats, we noticed that the adapters aren't properly tested this way.
The validation of `Extensions` can be disabled via the flag
`--dont-check-extensions` or the keyword argument `check_extensions` to
`AASDataChecker`, since many users are probably only interested in
comparing the main model, without any extensions.
Furthermore, the deserialization is fixed.
> compliance_tool: add verification and fix deserialization of `Extensions`

- test/adapter/xml/test_xml_deserialization.py
These comments were mistakenly re-added in a previous merge of main into improve/V30.
> test.adapter.xml: remove 'type: ignore' comments

- setup.py
We forgot to adapt the `setup.py` with the new version. 
This fixes this issue.
> setup.py: Bump to 1.0.0

- basyx/aas/model/datatypes.py
- test/model/test_datatypes.py
The current implementation use the abs function to check the value be inside the range. But the range is not symetric for example [byte ](https://www.w3.org/TR/xmlschema11-2/#byte) is between [-128,127] the value of [·maxInclusive·](https://www.w3.org/TR/xmlschema11-2/#dt-maxInclusive) to be 127 and [·minInclusive·](https://www.w3.org/TR/xmlschema11-2/#dt-minInclusive) to be -128`
> Fix negative xsd range edge cases

- basyx/aas/model/datatypes.py
- test/model/test_datatypes.py
This backports 7369d2ec7bec0bb0c873b367ffd1a833d01b6bdc to `v2.0.1`: 
>The current implementation uses the `abs()` function to check that the value is inside the range.
>However, the range is not symmetric.
>For example, for a [byte](https://www.w3.org/TR/xmlschema11-2/#byte), which is between [-128, 127],
>the value of
>[maxInclusive](https://www.w3.org/TR/xmlschema11-2/#dt-maxInclusive) should be 127,
>and [minInclusive](https://www.w3.org/TR/xmlschema11-2/#dt-minInclusive)
> should be -128.
> backport: Fix negative xsd range edge cases (#178)

- .github/workflows/ci.yml
- README.md
This adds a CI check, which uses the python package `codeblocks` to extract all python codeblocks from the readme to check them with `mypy` and `pycodestyle`, and also run them with `python` itself.
Fixes #124
> ci: add readme codeblock checks

- .github/workflows/ci.yml
- README.md
This backports #182 to `v2.0.1`:
>This adds a CI check, which uses the python package `codeblocks` to extract all python codeblocks from the readme to check them with `mypy` and `pycodestyle`, and also run them with `python` itself.
> backport: ci: add readme codeblock checks

- basyx/aas/examples/tutorial_storage.py
Previously this simply duplicated the previous assertion used to check the result of `obj_store.get_identifiable()`.
Fix #186
> examples.tutorial_storage: fix assertion

- basyx/aas/adapter/xml/xml_deserialization.py
Previously, if the elements of an XML document are part of an unknown
namespace, this would lead to cryptic error messages such as:
Unexpected top-level list aas:assetAdministrationShells on line 3
where, the correct expected element is indeed
aas:assetAdministrationShells, leaving the user wondering about what
could possibly be wrong. The only difference is the namespace, which
isn't part of the error message, because it gets replaced by the prefix.
To improve the error messages in this case, a check that compares the
namespaces declared on the document against the ones required by the
deserialization, and errors if a required namespace isn't declared.
Furthermore, the namespace of an element would always be replaced by its
prefix if the prefix is known. However, this turned out to mask …
> adapter.xml: improve error messages in case of incorrect namespace declarations

- basyx/aas/adapter/xml/xml_deserialization.py
Previously, if the elements of an XML document are part of an unknown
namespace, this would lead to cryptic error messages such as:
Unexpected top-level list aas:assetAdministrationShells on line 3
where, the correct expected element is indeed
aas:assetAdministrationShells, leaving the user wondering about what
could possibly be wrong. The only difference is the namespace, which
isn't part of the error message, because it gets replaced by the prefix.
To improve the error messages in this case, a check that compares the
namespaces declared on the document against the ones required by the
deserialization, and errors if a required namespace isn't declared.
Furthermore, the namespace of an element would always be replaced by its
prefix if the prefix is known. However, this turned out to mask …
> backport: adapter.xml: improve error messages in case of incorrect namespace declarations

- README.md
- docs/add-requirements.txt
- requirements.txt
This removes the unnecessary `psutil` dependency and the duplicate dependency on `sphinx` and its extensions. Furthermore, the `sphinx` packages are updated to the latest version.
> cleanup and update dependencies

- basyx/aas/examples/tutorial_storage.py
Previously this simply duplicated the previous assertion used to check the result of `obj_store.get_identifiable()`.
> backport: examples.tutorial_storage: fix assertion

- basyx/aas/__init__.py
- docs/source/conf.py
- setup.py
This moves the version declaration to the basyx.aas module and imports it from there in the docs configuration and setup.py. This avoid having to change the version number in multiple locations.
> move version declaration to basyx.aas module

- .github/workflows/ci.yml
This avoids having to update the CI python version in multiple places.
> ci: use `X_PYTHON_VERSION` for package job

- basyx/aas/adapter/aasx.py
- basyx/aas/compliance_tool/compliance_check_aasx.py
- test/compliance_tool/test_compliance_check_aasx.py
A `FileNotFoundError` is no longer converted to a `ValueError`, but re-raised instead. Furthermore, the message of the `ValueError` now contains more information as to why a file is not a valid OPC package.
Fix #221
> adapter.aasx: improve error messages

- setup.py
Following the guidelines of https://pypi.org/classifiers/ our current development status should not be "alpha", but "Production/Stable"
Fix #223
> setup: Update development status to Production/Stable

- basyx/aas/adapter/aasx.py
Replace a block of text by an `attention` admonition to highlight it properly. Furthermore, add a missing comma.
> adapter.aasx: improve `AASXWriter` docstring

- basyx/aas/adapter/xml/xml_deserialization.py
- test/adapter/xml/test_xml_deserialization.py
The type of an exception is changed from `TypeError` to `AssertionError`. The exception marks an error in the program, the previous declaration as `TypeError` was incorrect.
Furthermore, a test for XML without namespace prefixes is added, which wasn't tested previously (see #33).
> `adapter.xml`: minor improvements

- basyx/aas/adapter/xml/xml_deserialization.py
`GlobalReference` has been renamed to `ExternalReference` in V3, but this enum member has been missed in the rename.
This is technically a breaking change (which is why I pushed it to a separate branch), but I doubt that anyone really uses the deserialization of single objects, most people can't even use the normal deserialization due to wrong XML namespaces and OPC relationship types.
> adapter.xml: rename `XMLConstructables.GLOBAL_REFERENCE`

- README.md
- basyx/aas/adapter/_generic.py
- basyx/aas/adapter/json/json_deserialization.py
- basyx/aas/adapter/json/json_serialization.py
- basyx/aas/adapter/xml/__init__.py
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- basyx/aas/examples/tutorial_serialization_deserialization.py
- test/adapter/json/test_json_serialization_deserialization.py
- test/adapter/xml/test_xml_deserialization.py
- test/adapter/xml/test_xml_serialization_deserialization.py
lxml supports paths already, no modification is necessary there.
However, the `lxml.etree.ElementTree.write()` function requires
`BinaryIO`, i.e. files opened with the 'b' mode. While it would be
possible to access the underlying binary buffer of files opened in text
mode via `open()`, this isn't possible for `io.StringIO()`, as it
doesn't have the `buffer` property. Thus, even if we could support files
opened via `open()` in text mode, we couldn't annotate the XML
serialization functions with `TextIO`, as `io.StringIO()` remains
unsupported. Because of that, I decided to not support `TextIO` for the
XML serialization.
The builtin JSON module only supports file handles, with the
`json.dump()` method only supporting `TextIO` and `json.load()`
supporting `TextIO` and `BinaryIO`. Thus, the …
> `adapter.{json,xml}`: make (de-)serialization interfaces coherent

- basyx/aas/model/base.py
- test/model/test_base.py
Resolution of id_short paths is added via `UniqueIdShortNamespace.get_referable()`, such that it can be used on every object, that spans such a namespace. `ModelReference.resolve()` is simplified to make use of this new functionality. Furthermore, tests for this are added.
Fix #214
> model.base: add id_short path resolution

- basyx/aas/backend/couchdb.py
- basyx/aas/backend/local_file.py
- basyx/aas/model/base.py
- basyx/aas/model/provider.py
These are unsafe, according to mypy:
```
error: Call to abstract method "__init__" of "DataSpecificationContent" with trivial body via super() is unsafe  [safe-super]
```
> backend, model: remove calls to trivial super().__init__() methods

- basyx/aas/backend/couchdb.py
- basyx/aas/backend/local_file.py
- basyx/aas/model/base.py
- basyx/aas/model/provider.py
These are unsafe, according to mypy:
```
error: Call to abstract method "__init__" of "DataSpecificationContent" with trivial body via super() is unsafe  [safe-super]
```
This is a backport of #261.
> backport: backend, model: remove calls to trivial super().__init__() methods

- basyx/aas/adapter/aasx.py
- test/adapter/aasx/test_aasx.py
`AbstractSupplementaryFileContainer` and `DictSupplementaryFileContainer` are extended by a `delete_file()` method, that allows deleting files from them. Since different files may have the same content, references to the files contents in `DictSupplementaryFileContainer._store` are tracked via `_store_refcount`. A files contents are only deleted from `_store`, if all filenames referring to these these contents are deleted, i.e. if the refcount reaches 0.
> adapter.aasx: allow deleting files from `SupplementaryFileContainer`

- docs/source/conf.py
Since `PyECMA376-2` doesn't have a documentation we can link to, we ignore missing reference warnings caused by this problem. The visibility of this workaround is improved by making it a `TODO` instead of a regular comment. Furthermore, it now links to the corresponding issue.
> docs: improve the documentation of the `PyECMA376-2` intersphinx workaround

- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- docs/source/conf.py
- requirements.txt
- test/adapter/xml/test_xml_deserialization.py
- test/adapter/xml/test_xml_serialization.py
`lxml` provides type annotations via the `lxml-stubs` package. By using this package, we don't need the `type: ignore` comments when importing `lxml` anymore. Furthermore, the typehints are adjusted: `etree.Element` is only a factory function that creates `etree._Element` instances.
Finally, when generating the docs we introduced a workaround that makes linking to the `lxml` documentation possible. Since it only replaced lookups for `Element` with `_Element`, it isn't necessary anymore and removed.
> add `lxml` typechecking

- test/model/test_concept.py
Previously, the module `model.concept` didn't 
have any unittests.
This adds the test file for `model.concept` and
specifically adds a test for `_set_category`.
> test.model.test_concept: Add test file for model.concept

- test/adapter/xml/test_xml_deserialization.py
Added new tests covering the `_tag_replace_namespace` function in `xml_deserialisation.py` therefore improving test coverage:
Before:
```
basyx\aas\adapter\xml\xml_deserialization.py                     764     83    458     60    85% 90->89, 92,
```
After:
```
basyx\aas\adapter\xml\xml_deserialization.py                     764     82    458     58    86%
```
> test_xml_deserialization: Add tests for `_tag_replace_namespace`

- basyx/aas/adapter/json/json_deserialization.py
- basyx/aas/adapter/json/json_serialization.py
- basyx/aas/adapter/xml/xml_deserialization.py
- basyx/aas/adapter/xml/xml_serialization.py
- basyx/aas/backend/couchdb.py
- basyx/aas/backend/local_file.py
- basyx/aas/model/base.py
- basyx/aas/model/provider.py
The methods for handling attributes of abstract classes seemed to me too big. 
In this PR these methods are refactored.  Mostly a method extraction refactoring was done, to simplify the methods and to keep less abstraction levels in a single method
The function `_expect_type` was renamed to `_is_of_type` as it represents clearer what the func does.
This PR is not relevant for the V3.0 release and can be merged later
> adapter: Refactor XML and JSON de-/serialization methods

- basyx/aas/adapter/http.py
- Refactored handling of get_response_type(): 
To remove get_response_type() in the beginning of all endpoint funcs I have integrate it in handle_request() and added an arg for response type in all endpoint funcs.
- Refactored _get_submodel_or_nested_submodel_element():
It has only `url_args` now as an argument and returns the se or a submodel. 
Before it had a `submodel` and `id_shorts` in arguments, so in all funcs which used it a submodel and id_short_path were explored with separate funcs.
Depends on #291
> `adapter.http`: refactor

- basyx/aas/backend/couchdb.py
- pyproject.toml
- requirements.txt
The previous version contraint `urllib3>=1.26,<2.0` is verry restrictive.
I need to use the SDK in a project together with other libs (e.g. gradio) that require urlib3 >= 2.
I widened the version constraint according to [urllib3 migration guide](https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#migrating-as-a-package-maintainer) and did't see any deprecation warnings (hopefully i turned them on correctly).
> aas.backend: Support urllib3 version 2

- basyx/aas/model/datatypes.py
- test/model/test_datatypes.py
Currently, the copy of a submodel with Date properties using pythons built-in `copy.copy` or `copy.deepcopy` fails with the following error:
>  File "basyx-python-sdk\basyx\aas\model\datatypes.py", line 49, in __new__
>    res: "Date" = datetime.date.__new__(cls, year, month, day)  # type: ignore  # pickle support is not in typeshed
>TypeError: 'bytes' object cannot be interpreted as an integer
The error can be reproduced with (see test added in this PR):
```py
import copy
from basyx.aas import model
date = model.datatypes.Date(2020, 1, 24)
date_copy_shallow = copy.copy(date) # will Fail
date_copy_deep = copy.deepcopy(date) # will Fail
```
I don't know where the error comes from, but when the class is copied the `year` argument gets a bytestring and `month` as well as `day`are `None`. …
> model.datatypes: fix error when copy Dates

- basyx/aas/adapter/rdf/rdf_serialization.py
- pyproject.toml
- test/adapter/rdf/test_rdf_serialization.py
Previously, we used version 0.26.0 of pyshacl. This version however had a problem with typing, namely the `py.typed` file was in the wrong location (see [pyshacl#267](https://github.com/RDFLib/pySHACL/issues/267)).
This has been fixed in this new release, therefore we bump the version number in our dependency declaration.
This also should fix our CI Pipeline in the RDF branch, as we both fix the mypy issues, as well as some pycodestyle ones.
> pyproject.toml: Update version for pyshacl

- README.md
We fix a broken link in the toplevel `README.md`,  namely the one to the `CONTRIBUTING.md`
Fixes #321
> Fix "contributing" link in README.md

- CONTRIBUTING.md
With changing the repository structure, the instructions on checking codestyle and tests did become a little less clear. 
In order to avoid confusion, we update the instructions with a note.
Fixes #325
> CONTRIBUTING.md: Update instructions

- README.md
- sdk/basyx/aas/model/_string_constraints.py
This updates the `sdk` to version 3.0.1 of the metamodel. Since this was a minor bugfix release, there are only a handful of changes and only one that actually affects our SDK (as the rest of the changes were editorial):
Remove the pattern check from `PathType`. Effectively, that means we remove the pattern from the  `_string_constraints.check_path_type` method. See: [aas-core#334](https://github.com/aas-core-works/aas-core-meta/pull/334).
Furthermore, we update the version table in the `README.md`.
Here's the link to the [specification changelog](https://industrialdigitaltwin.org/wp-content/uploads/2024/06/IDTA-01001-3-0-1_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=150)
> Update to Part 1 (Metamodel) version 3.0.1

- .github/workflows/ci.yml
Expand ci to also test the server. Only tests if server can be build and run for now.
I also upgraded from `actions/checkout@v2` to `actions/checkout@v4`.
> workflows:  Add server ci, upgrade to @v4

- .github/workflows/ci.yml
- etc/scripts/check_python_versions_coincide.py
- etc/scripts/check_python_versions_requirements.txt
- etc/scripts/check_python_versions_supported.py
- sdk/basyx/aas/adapter/http.py
- sdk/pyproject.toml
This bumps the `requires-python` field in the `pyproject.toml` of the SDK from `">=3.8"` to `">=3.9"`, due to the fact that Python v3.8 reached EoL on 2024-10-07.
Furthermore, to avoid future backward compatibility issues with the supported Python versions, as well as to ensure we're always supporting the currently supported Python versions, we add a CI check `check-python-versions` that uses two new scripts in `./etc/scripts` to check:
a) our currently supported Python versions to an EoL database
b) that our currently supported Python versions defined in the CI match the ones in the `pyproject.toml`.
This should ensure that issues like #330 are avoided in the future.
adapter.http: Fix reference to constant from the future
Currently, we're using `datetime.UTC`, a constant defined in the …
> SDK: Bump required Python version to >= 3.9, Add version CI check

- sdk/basyx/aas/adapter/xml/xml_deserialization.py
- Added _get_text_or_empty_string_or_none(), which returns an empty string if the text is None.
- Used the new function for all attributes that can be empty strings. In particular, this affects all the attributes of one of XSD_TYPE_CLASSES type, as they can be strings including the empty string.
Fixes #242
> basyx.adapter: Allow empty strings in XML deserialization for some attrs

- README.md
Previously, we did not advertise the existence of the RDF serializer in our `README.md`. 
This adds a reference to this experimental feature and where to find it.
> Add Reference to RDF serializer to README.md

- .github/workflows/release.yml
During the release process, the distribution files are currently built in the `sdk/dist/` directory, however the PyPI action expects them in the top-level `dist` directory.
Therefore we adapt the build path in the workflow.
> .github/workflows: Fix dist path in release.yml

- sdk/README.md
The README.md currently still has refrences to the deleted requirements.txt. These are removed.
> sdk/README.md: update README.md

- basyx/aas/adapter/rdf/rdf_serialization.py
Previously, there was a trailing slash (`/`) missing in the AAS namespace resulting in invalid URIs, e.g.:
```
https://admin-shell.io/aas/3/0Identifiable/
```
instead of: 
```
https://admin-shell.io/aas/3/0/Identifiable/
```
This adds the trailing slash to the namespace in`the RDF serializer.
Fixes #365
> adapter.rdf: Add trailing slash to AAS namespace

- .github/workflows/ci.yml
- compliance_tool/aas_compliance_tool/cli.py
- compliance_tool/aas_compliance_tool/compliance_check_aasx.py
- compliance_tool/aas_compliance_tool/compliance_check_json.py
- compliance_tool/aas_compliance_tool/compliance_check_xml.py
- compliance_tool/aas_compliance_tool/state_manager.py
- compliance_tool/setup.py
- compliance_tool/test/files/test_demo_full_example.json
- compliance_tool/test/files/test_demo_full_example.xml
- compliance_tool/test/files/test_demo_full_example_json_aasx/aasx/data.json
- compliance_tool/test/files/test_demo_full_example_wrong_attribute.json
- compliance_tool/test/files/test_demo_full_example_wrong_attribute.xml
- compliance_tool/test/files/test_demo_full_example_xml_aasx/aasx/data.xml
- compliance_tool/test/files/test_demo_full_example_xml_wrong_attribute_aasx/aasx/data.xml
- compliance_tool/test/test_aas_compliance_tool.py
- compliance_tool/test/test_compliance_check_aasx.py
- compliance_tool/test/test_compliance_check_json.py
- compliance_tool/test/test_compliance_check_xml.py
- compliance_tool/test/test_state_manager.py
Currently there are quite some wrong imports in the compliance-tool directory. Even when those are fixed many Unitests still fail.
Here these imports are fixed.
Fixes https://github.com/eclipse-basyx/basyx-python-sdk/issues/354
> compliance-tool: Fix compliance tool imports and unitests

- sdk/pyproject.toml
This updates the minimum version of the dependency `pyecma376` in the `pyproject.toml`, ensuring that our AASX files allow for spaces in file names. 
Fixes #236
> sdk: Update version of pyecma dependency in pyproject.toml

- sdk/README.md
- sdk/pyproject.toml
Some `sdk` dependencies, that are only necessary for testing, are included in the mandatory dependencies.
The development dependencies can be moved to the existing optional-dependencies  `dev` section, to make the library footprint smaller, when it is used without modifications.
I assume following deps can be moved:
* schemathesis: imported in `test_http.py`
* jsonschema: imported in `test_http.py` and `test_json_serialization.py`
* hypothesis: imported in `test_http.py`
* types-python-dateutil: used for typechecking
* lxml-stubs: used for typechecking
> sdk.deps: Move test depencies to extra dev section

- sdk/.readthedocs.yaml
We were still trying to install dependencies from the already deleted requirements.txt, now they are being installed from the pyproject.toml.
> sdk/.readthedocs.yaml: install dependencies from pyproject.toml

- CONTRIBUTING.md
Previously, the section "Codestyle and Testing" was outdated, still from the time where there was only the SDK inside this repository.
This greatly extends the section, renaming it to "Code Quality" and introducing subsections for "Codestyle" and "Testing", where we describe how to run the necessary tests locally on the developer's machine for each of the packages inside this monorepository.
Fixes #353
> CONTRIBUTING.md: Improve codestyle and testing section

- .github/workflows/release.yml
This adds a job `compliance-tool-publish` to the `release.yml` that automatically publishes the compliance-tool package to PyPI upon release. It is simply copied from the SDK job, with adapted paths.
> Add CI job to release compliance-tool to PyPI

- sdk/basyx/aas/adapter/aasx.py
There are many AASX in the wild where there is an additional `www` in the relationship definition that does not belong there:
```
http://www.admin-shell.io/aasx/relationships/aasx-origin
```
whereas it should be according to the [specification](https://industrialdigitaltwin.org/wp-content/uploads/2024/06/IDTA-01005-3-0-1_SpecificationAssetAdministrationShell_Part5_AASXPackageFileFormat.pdf#Page=18):
```
http://admin-shell.io/aasx/relationships/aasx-origin
```
Previously, our SDK did not allow for reading these AASX files with wrong relationship URL. 
However, since there are so many of them, this change enables them to be read, while notifying the user with a big warning message that their AASX file is actually not standard compliant and needs to be changed (see discussion in #381).
Fixes …
> adapter.aasx: Allow reading AASX with wrong relationship

- .github/workflows/ci.yml
- sdk/docs/add-requirements.txt
Currently, the sphinx dependencies in `docs/add_requirements.txt` are outdated, causing our CI pipeline to fail.
This bumps the versions for the additional requirements for the compilation of the documentation to their newest working state. Since that version needs `Python >= 3.11`, we also need to bump the version of Python used in the CI.
Fixes #385
> sdk/docs: Bump versions for sphinx dependencies

- sdk/basyx/aas/adapter/aasx.py
- sdk/basyx/aas/adapter/json/json_deserialization.py
- sdk/basyx/aas/adapter/xml/xml_deserialization.py
Previously, the `failsafe` parameter, allowing to skip errors and only log them as warnings instead, only existed for JSON and XML (de-)serialization. 
This PR extends the feature to also be included when reading and writing AASX files. 
For this, we add the `failsafe` boolean attribute to the `AASXReader` and `AASXWriter` classes in `adapter.aasx`. 
If `failsafe` is `True`, the document is parsed in a failsafe way: Missing attributes and elements are logged instead of causing exceptions. Defect objects are skipped. The default value is `False`, keeping the existing behavior.
Furthermore, we do a little code-style clean up on string-formatting in the `adapter.aasx` module, updating all occurrences from (historically) different syntaxes to the more modern f-string syntax.
Fixes #228
> aasx.py: Add failsafe for writing and reading AASX files

- sdk/pyproject.toml
Previously, the `lxml` dependency in the `pyproject.toml` was pinned to versions `>=4.2,<5`. This caused a faulty installation via `pip` on Windows due to missing binary wheels. Moreover, the `mypy` dependency was unpinned, leading to the installation of the latest version. The recent release of `mypy 1.16.0` introduced changes not yet supported by our codebase, resulting in CI pipeline failures.
This updates the `lxml` dependency to versions `>=5.3` to resolve the installation issue. Additionally, this restricts the `mypy` dependency to version `1.15.0` until we have proper support for `1.16.0` and its new features.
Fixes #391
> sdk: Update lxml and mypy dependency in pyproject.toml

- sdk/basyx/aas/adapter/xml/xml_serialization.py
- sdk/basyx/aas/model/base.py
- sdk/basyx/aas/model/submodel.py
Previously, the release of `mypy 1.16` added new features for the type check, resulting in our pipeline to fail.
This refactors the codebase to comply with `mypy 1.16`. Instances where `# type: ignore` was necessary are documented with context.
Fixes #390
> sdk/basyx/aas: Fix type issues under mypy 1.16

- server/README.md
Previously, #386 proposed narrowing the scope of the build context for `server/Dockerfile` to `/server`. As a consequence, `/sdk`, which is required to build the server, would no longer be accessible. Locally, this would necessitate explicitly referencing `/sdk` as a second build context. When using the GitHub URL of this repository as build context instead of a local repository, this would additionally lead to inefficient data handling. Since Docker Compose does not yet support sparse checkouts, specifying subdirectories like `/server` as build context still results in the full repository being cloned. Consequently, although `/sdk` would be downloaded, it would be excluded from the narrowed build context and thus remain unavailable. Any attempt to include `/sdk` separately afterwards …
> server/README.md: Clarify Docker build context

- server/app/main.py
- Refactor imports
- Fix the reading of json and xml files
We use now FileIO as input for `read_aas_xml_file_into` as we do in `read_aas_json_file_into`. 
I have checked it and it worked
> Small fixes in `server\app\main.py`
